"""
Relier Core — Schema Versioning.

Provides versioned task envelopes, payload integrity verification, and
rolling-schema migration support for in-flight Celery tasks.

The schema subsystem enables zero-downtime deployments by allowing
workers running newer code to safely process payloads generated by
older application versions.

Features
--------
- versioned execution envelopes
- cryptographic payload integrity verification
- sequential schema migrations
- forward-compatible rolling deployments
- strict envelope validation via Pydantic
"""

import hashlib
import json
import logging
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field

from relier.core.exceptions import PayloadIntegrityError

logger = logging.getLogger(__name__)


class TaskEnvelope(BaseModel):
    """
    Canonical schema for serialized task envelopes.

    Validation occurs before payload processing to prevent malformed,
    tampered, or structurally incompatible task data from entering the
    execution pipeline.
    """

    task_id: str = Field(..., min_length=1, max_length=128, pattern=r"^[a-zA-Z0-9_-]+$")
    schema_version: int = Field(..., ge=1, le=100)
    payload: dict
    checksum: str
    enqueued_at: str


class SchemaRegistry:
    """
    Coordinates envelope serialization, integrity verification, and
    cross-version payload migrations.

    Migration handlers are registered globally so all worker processes share
    a consistent upgrade path for persisted task payloads.
    """

    # Current envelope schema version.
    #
    # Increment whenever a task payload change introduces a backward-
    # incompatible execution contract requiring migration support.
    CURRENT_VERSION = 1

    # Registry of sequential migration handlers indexed by:
    #   {task_name -> {from_version -> migration_callable}}
    _migrations: dict[str, dict[int, Callable]] = {}

    @classmethod
    def register_migration(cls, task_name: str, from_version: int) -> Callable:
        """
        Register a payload migration handler for a task schema version.

        Migration handlers transform older payload formats into the next
        compatible schema revision during task replay or execution recovery.

        Example::

            @SchemaRegistry.register_migration("my_task", from_version=1)
            def migrate_v1_to_v2(args, kwargs):
                kwargs["new_required_arg"] = "default_value"
                return args, kwargs
        """

        def decorator(func: Callable[[tuple, dict], tuple[tuple, dict]]) -> Callable:
            """Register the migration callable in the global schema registry."""
            if task_name not in cls._migrations:
                cls._migrations[task_name] = {}
            cls._migrations[task_name][from_version] = func
            return func

        return decorator

    @classmethod
    def _generate_checksum(cls, payload: dict[str, Any]) -> str:
        """
        Generate a deterministic SHA-256 checksum for a task payload.

        Payloads are serialized with stable key ordering so integrity hashes
        remain reproducible across workers and deployment environments.
        """
        payload_str = json.dumps(payload, sort_keys=True, default=str)
        return f"sha256:{hashlib.sha256(payload_str.encode()).hexdigest()}"

    @classmethod
    def wrap(cls, task_id: str, args: tuple, kwargs: dict) -> dict[str, Any]:
        """
        Serialize task arguments into a versioned execution envelope.

        The resulting envelope contains:
        - schema version metadata
        - integrity verification data
        - enqueue timestamps
        - serialized execution arguments
        """
        payload = {"args": args, "kwargs": kwargs}

        return {
            "schema_version": cls.CURRENT_VERSION,
            "task_id": task_id,
            "payload": payload,
            "enqueued_at": datetime.now(UTC).isoformat(),
            "checksum": cls._generate_checksum(payload),
        }

    @classmethod
    def unwrap_and_migrate(
        cls, task_name: str, envelope: dict[str, Any]
    ) -> tuple[tuple, dict]:
        """
        Validate, verify, and upgrade a serialized task envelope.

        This method performs the full inbound compatibility pipeline:
        - strict schema validation
        - checksum verification
        - payload extraction
        - sequential migration application
        """
        # Validate envelope structure before any payload processing occurs.
        try:
            valid_envelope = TaskEnvelope.model_validate(envelope)
        except Exception as e:
            logger.critical(
                "Rejected malformed task envelope.",
                extra={"error": str(e)},
            )
            raise PayloadIntegrityError(f"Invalid envelope structure: {e}") from e

        version = valid_envelope.schema_version
        payload = valid_envelope.payload
        task_id = valid_envelope.task_id

        # Fail fast if payload integrity verification does not match.
        expected_checksum = cls._generate_checksum(payload)
        if expected_checksum != valid_envelope.checksum:
            logger.critical(
                "Task payload integrity verification failed.",
                extra={
                    "task_id": task_id,
                    "expected": expected_checksum,
                    "actual": envelope.get("checksum"),
                },
            )
            # Abort execution immediately so corrupted payloads are quarantined
            # instead of entering the worker execution pipeline.
            raise PayloadIntegrityError(f"Payload checksum mismatch for task {task_id}")

        # Restore positional arguments back to tuple form after JSON decoding.
        args = tuple(payload.get("args", []))
        kwargs = payload.get("kwargs", {})

        # Apply incremental migrations until the payload reaches the current
        # runtime schema version.
        while version < cls.CURRENT_VERSION:
            if task_name in cls._migrations and version in cls._migrations[task_name]:
                logger.info(
                    "Applying task payload migration.",
                    extra={
                        "task_name": task_name,
                        "from_version": version,
                        "to_version": version + 1,
                    },
                )
                migrator = cls._migrations[task_name][version]
                try:
                    args, kwargs = migrator(args, kwargs)
                except Exception as e:
                    logger.error(
                        "Task payload migration failed.",
                        extra={
                            "task_name": task_name,
                            "from_version": version,
                            "to_version": version + 1,
                            "error": str(e),
                        },
                    )
                    raise  # Propagate the failure so the task can be quarantined safely.
            else:
                logger.warning(
                    "No schema migration registered; using payload without transformation.",
                    extra={"task_name": task_name, "version": version},
                )
            version += 1

        return args, kwargs
