"""
Relier Core — Schema Versioning.

Wraps Celery task payloads in a versioned envelope. Provides automatic
data migration for in-flight tasks during zero-downtime rolling deployments,
along with cryptographic integrity checks.
"""

import hashlib
import json
import logging
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field

from relier.core.exceptions import PayloadIntegrityError

logger = logging.getLogger(__name__)


class TaskEnvelope(BaseModel):
    """Strict validation for inbound task payloads."""

    task_id: str = Field(..., min_length=1, max_length=128, pattern=r"^[a-zA-Z0-9_-]+$")
    schema_version: int = Field(..., ge=1, le=100)
    payload: dict
    checksum: str
    enqueued_at: str


class SchemaRegistry:
    """
    Manages task envelopes, payload integrity, and data migrations.
    Operates as a class-level singleton to track migrations globally.
    """

    # Current version of the system. Bump this when adding required arguments to tasks.
    CURRENT_VERSION = 1

    # Map of { task_name: { from_version: migration_function } }
    _migrations: dict[str, dict[int, Callable]] = {}

    @classmethod
    def register_migration(cls, task_name: str, from_version: int) -> Callable:
        """
        Decorator for users to define how to upgrade an old payload.

        Usage:
            @SchemaRegistry.register_migration("my_task", from_version=1)
            def migrate_v1_to_v2(args, kwargs):
                kwargs["new_required_arg"] = "default_value"
                return args, kwargs
        """

        def decorator(func: Callable[[tuple, dict], tuple[tuple, dict]]) -> Callable:
            if task_name not in cls._migrations:
                cls._migrations[task_name] = {}
            cls._migrations[task_name][from_version] = func
            return func

        return decorator

    @classmethod
    def _generate_checksum(cls, payload: dict[str, Any]) -> str:
        """
        Safely generates a SHA-256 checksum for the payload, handling complex
        types like UUIDs and datetimes gracefully via default=str.
        """
        payload_str = json.dumps(payload, sort_keys=True, default=str)
        return f"sha256:{hashlib.sha256(payload_str.encode()).hexdigest()}"

    @classmethod
    def wrap(cls, task_id: str, args: tuple, kwargs: dict) -> dict[str, Any]:
        """
        Wrap raw arguments in a secure, versioned envelope before enqueueing.
        """
        payload = {"args": args, "kwargs": kwargs}

        return {
            "schema_version": cls.CURRENT_VERSION,
            "task_id": task_id,
            "payload": payload,
            "enqueued_at": datetime.now(UTC).isoformat(),
            "checksum": cls._generate_checksum(payload),
        }

    @classmethod
    def unwrap_and_migrate(
        cls, task_name: str, envelope: dict[str, Any]
    ) -> tuple[tuple, dict]:
        """
        Unwrap the envelope, verify integrity, and apply migrations if
        the task was generated by older code.
        """
        # Validate input envelope using Pydantic to prevent injection
        try:
            valid_envelope = TaskEnvelope.model_validate(envelope)
        except Exception as e:
            logger.critical(
                "Invalid envelope structure.",
                extra={"error": str(e)},
            )
            raise PayloadIntegrityError(f"Invalid envelope structure: {e}") from e

        version = valid_envelope.schema_version
        payload = valid_envelope.payload
        task_id = valid_envelope.task_id

        # Verify Cryptographic Integrity (Fail fast on corruption)
        expected_checksum = cls._generate_checksum(payload)
        if expected_checksum != valid_envelope.checksum:
            logger.critical(
                "Integrity check failed.",
                extra={
                    "task_id": task_id,
                    "expected": expected_checksum,
                    "actual": envelope.get("checksum"),
                },
            )
            # Raise here to prevent processing corrupted data.
            # The Relier DLQ mechanism will catch this and quarantine the payload.
            raise PayloadIntegrityError(f"Payload checksum mismatch for task {task_id}")

        # Extract arguments (JSON decodes tuples as lists, so we cast args back)
        args = tuple(payload.get("args", []))
        kwargs = payload.get("kwargs", {})

        # Apply migrations sequentially until we reach CURRENT_VERSION
        while version < cls.CURRENT_VERSION:
            if task_name in cls._migrations and version in cls._migrations[task_name]:
                logger.info(
                    "Migrating payload.",
                    extra={
                        "task_name": task_name,
                        "from_version": version,
                        "to_version": version + 1,
                    },
                )
                migrator = cls._migrations[task_name][version]
                try:
                    args, kwargs = migrator(args, kwargs)
                except Exception as e:
                    logger.error(
                        "Migration failed.",
                        extra={
                            "task_name": task_name,
                            "from_version": version,
                            "to_version": version + 1,
                            "error": str(e),
                        },
                    )
                    raise  # Let it fail so it goes to the DLQ
            else:
                logger.warning(
                    "No migration found. Passing arguments as-is.",
                    extra={"task_name": task_name, "version": version},
                )
            version += 1

        return args, kwargs
